openapi: 3.0.3
tags:
  - "Requests pipeline"
summary: "Returns the ontology made by the TLA pipeline directly from arxiv API with X papers"
description: "This route allows the user to get the result of ontology processing made directly from arxiv. It can take a long time.Because it's process directly all the papers. Don't take in count the TypeError: Network error because it takes times"
produces:
- "application/file"
parameters:
      - name: nb_paper
        in: path
        type: string
        required: true
responses:
        '200':
          schema:
            type: file
          headers:
            Content-type:
              type: string
              description: text/owl; charset=utf-8
            Content-Disposition:
              type: string
              description: attachment; filename=onto10_done.owl
          description: Export ontology into a owl file

        '400':
          description: "Problem while created the ontology "

        '404':
          description: "Ontology not found"