openapi: 3.0.3
tags:
  - "Size database"
summary: "Return the size of the database"
description: "Return the size of the database"
produces:
- "application/json"
responses:
        '200':
          description: "Successful response"
          schema:
            type: "json"
                
        '400':
              description: "Problem occurs when requesting the database"
              schema:
                type: "json"