openapi: 3.0.3
tags:
  - "Size database"
summary: "Returns the size of the database"
description: "Returns the size of the SqlAchemy database :bddarxiv.db"
produces:
- "application/json"
responses:
        '200':
          description: "Successful response"
                
        '400':
              description: "Problem occurs when requesting the database"